from typing import TypedDict
from pydantic import BaseModel, Field

class SQLQueryOutput(BaseModel):
    """Structured output expected from the LLM generating the SQL."""
    sql_query: str = Field(
        description="The generated executable SQL query."
    )
    explanation: str = Field(
        description="A brief explanation of the logic behind the SQL query."
    )

class AgentState(TypedDict):
    """Operational memory for the LangGraph state machine."""
    
    # The initial natural language request provided by the user
    user_query: str
    
    # The current SQL query generated by the agent, to be executed or reviewed
    generated_sql: str
    
    # The database error message if the query fails (initialized/defaults to an empty string)
    execution_error: str
    
    # A counter to track how many times the agent has tried to fix a failing query (initialized/defaults to 0)
    retry_count: int
